### ISSUE TITLE
很赞，请教个技术

### ISSUE THREAD

**Issue by shijinliang** [Wildog/Gankee#2]
关于Share Extension的使用，研究过一段时间，遇到的问题也很多，
现在有一个例子：知乎里面的系统分享有掘金，这个怎么实现的？（目前咱这个APP可以支持浏览器分享到Gankee，如果知乎的系统分享中出现Gankee，还需要做些什么操作）

**Comment by Wildog** [comment]
这个跟我 info.plist 里面设置的 NSExtensionActivationRule 有关，我现在设置的只有 NSExtensionActivationSupportsWebURLWithMaxCount = 1，所以只有 URL 的 attachment 才能触发这个 share extension，我看了下知乎的分享除了 URL 还另外包含了一段描述文本，所以应该在 NSExtensionActivationRule 里再添加个 NSExtensionActivationSupportsText，具体试一下就知道了

**Comment by shijinliang** [comment]
好的，谢谢，测试OK
